### ISSUE TITLE
Select/Deselect All Collection filter button in Hoover

### ISSUE THREAD

**Issue by germakoci** [hoover/ui#16]
since there is UI work in progress for integrating the deduplication, could you also add the de/select all collections button [as explained here](https://github.com/liquidinvestigations/liquidinvestigations/issues/43) @mgax  ?

**Comment by mgax** [comment]
Fixed in https://github.com/hoover/ui/commit/43b59e4004b1c58a8c6040a6f2418b805027a5c6
