### ISSUE TITLE
UX and code improvements

### ISSUE THREAD

**Issue by jarib** [hoover/ui#22]
The UI is built with React, but doesn't really take advantage of the possibilities it provides. 

I would like to make the following changes:

* [x] Move to a single-page app where each new search does not submit the form and reload the page, but is background-fetched using XHR
* [x] Make a few design tweaks to make the UI easier on the eye
* [x] Bring code style more up to date with conventions in the React community.
* [ ] Set up a automated testing using Jest
* [x] Replace the custom config/build with a framework like Next.js (or Gatsby), where static site generation is built in.

The last suggestion is probably the most invasive, but I've had a great experience using Next.js when building the Norwegian fact-checking site [Faktisk.no](https://www.faktisk.no/). IMO it will greatly improve the ease of development going forward.

**Comment by mgax** [comment]
@jarib you're absolutely right, we never had time to really focus on the front-end, and the improvements you suggest make a lot of sense.

**Comment by jarib** [comment]
👍 I’ll move ahead then.
