### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by jarib** [hoover/ui#27]
Tree view integrated to the search results page.

(Perhaps the search page needs multiple tabs: search, batch search, tree view, facet explorer.)

**Comment by germakoci** [comment]
I agree, but at least the tree view should remain available also when opening a result in a new page; if you find something interesting, you maybe want to be able to see the entire tree view of that specific document in one glance

**Comment by germakoci** [comment]
@jarib also the tree view should show previews of the docs; for instance if you want to browse an email folder like you would do it in an email client, without opening each email

**Comment by jarib** [comment]
TODO:

* [ ] Keep parent folder contents in the left side bar when previewing an item

**Comment by jarib** [comment]
Ideally, we could have something like Finder's multi-column file navigation:

![image](https://user-images.githubusercontent.com/572/45627779-f39dd980-ba92-11e8-9c1a-ee3511d9145c.png)

**Comment by jarib** [comment]
Possible implementations:


https://ruoru.github.io/react-mac-finder/
https://frezc.github.io/react-finder/examples/basic.html

**Comment by jarib** [comment]
moved to eic
