### ISSUE TITLE
Batch search result will not open a new search

### ISSUE THREAD

**Issue by germakoci** [hoover/ui#38]
When using batch search, number of hits are listed below and the search terms that have hits are hyperlinked to open a new simple search in a new window. Currently this window is opening an empty batch search instead.

**Comment by jarib** [comment]
Hmm, I can't reproduce this on my Hoover instance. It opens a search with the linked query.

What URL do you see if you right-click and copy the link in the batch search? And what you end up on when you click it?

**Comment by germakoci** [comment]
ah, the instance I'm looking at must then pull the latest version @salevajo
