### ISSUE TITLE
Don't load assets from CDN

### ISSUE THREAD

**Issue by mgax** [hoover/ui#50]
The CDN [can read the URL](https://stackoverflow.com/a/30743967) from our page, which includes search terms, which we already decided not to log on our end.

The UI currently loads Google fonts:
https://fonts.googleapis.com/css?family=Open+Sans:300,400,500|Roboto+Condensed:300,400,500,
https://fonts.gstatic.com/s/opensans/v16/mem8YaGs126MiZpBA-UFVp0bbck.woff2

**Comment by gabriel-v** [comment]
#51 is closed
